package constants

const SCREEN_EXPLORE = "Explore"
const SCREEN_PROFILE = "Profile"
const SCREEN_HOME = "Home"

const NOTIFICATION_TYPE_COMMENT = "COMMENT"
const NOTIFICATION_TYPE_LIKE = "LIKE"

const NOTIFICATION_TYPE_COMMENT_LIKE = "COMMENT_LIKE"
const NOTIFICATION_TYPE_FOLLOW = "FOLLOW"
